apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      app: mysql
      tier: backend
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      containers:
      - image: mysql:5
        name: mysql
        env:
        - name: MYSQL_USER
          value: mydbuser
        - name: MYSQL_PASSWORD
          value: mydbpassword
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: 'yes'
        ports:
        - containerPort: 3306
          name: mysql
